from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import letter
from reportlab.lib.units import inch
from reportlab.lib.utils import ImageReader
import os
import time


def _format_datetime(timestamp):
    return time.strftime("%Y-%m-%d %H:%M:%S", time.localtime(timestamp))


def _risk_category(score):
    if score is None:
        return "N/A"
    if score >= 0.75:
        return "High risk"
    if score >= 0.50:
        return "Moderate risk"
    return "Low risk"


def _draw_footer(c, page_number, width):
    c.setFont("Helvetica", 8)
    c.setFillColorRGB(0.35, 0.35, 0.35)
    c.drawString(50, 30, "Disclaimer: This report is intended for clinical reference and should be reviewed by qualified medical personnel.")
    c.drawRightString(width - 50, 30, f"Page {page_number}")


def create_report(image_path, feature_dim, score=None, patient_info=None, features=None, recommendations=None, report_id=None):
    """Create a professional PDF report with patient details, analysis summary, and recommendations.

    Returns the generated report filename.
    """
    ts = int(time.time())
    report_id = report_id or f"RPT-{ts}"
    generated_at = _format_datetime(ts)
    report_name = f"report_{ts}.pdf"

    path = os.path.join("static", "reports", report_name)
    os.makedirs(os.path.dirname(path), exist_ok=True)

    width, height = letter
    c = canvas.Canvas(path, pagesize=letter)

    # Header
    c.setFont("Helvetica-Bold", 22)
    c.drawString(50, height - 60, "Chest X-ray Intelligence Report")
    c.setFont("Helvetica", 10)
    c.drawString(50, height - 80, "Generated by: Chest X-ray Intelligence Hub")
    c.drawRightString(width - 50, height - 60, f"Report ID: {report_id}")
    c.drawRightString(width - 50, height - 80, f"Date: {generated_at}")
    c.setLineWidth(1.5)
    c.line(50, height - 90, width - 50, height - 90)

    # Patient details
    c.setFont("Helvetica-Bold", 12)
    c.drawString(50, height - 120, "Patient details")
    c.setFont("Helvetica", 10)
    patient_id = patient_info.get("patient_id", "N/A") if patient_info else "N/A"
    patient_name = patient_info.get("name", "N/A") if patient_info else "N/A"
    patient_age = patient_info.get("age", "N/A") if patient_info else "N/A"
    patient_gender = patient_info.get("gender", "N/A") if patient_info else "N/A"
    patient_history = patient_info.get("history", "N/A") if patient_info else "N/A"

    c.drawString(60, height - 140, f"Patient ID: {patient_id}")
    c.drawString(60, height - 155, f"Name: {patient_name}")
    c.drawString(60, height - 170, f"Age: {patient_age}")
    c.drawString(60, height - 185, f"Gender: {patient_gender}")
    c.drawString(60, height - 200, "Clinical notes:")

    notes_text = str(patient_history) if patient_history is not None else "N/A"
    text = c.beginText(60, height - 215)
    text.setFont("Helvetica", 9)
    text.textLines(notes_text[:420])
    c.drawText(text)

    # Analysis summary
    summary_y = height - 310
    c.setFont("Helvetica-Bold", 12)
    c.drawString(50, summary_y, "Analysis summary")
    c.setFont("Helvetica", 10)
    c.drawString(60, summary_y - 20, "Model: SSL Encoder (Self-Supervised Learning)")
    c.drawString(60, summary_y - 35, f"Feature dimension: {feature_dim}")
    c.drawString(60, summary_y - 50, f"Abnormality score: {score if score is not None else 'N/A'}")
    c.drawString(60, summary_y - 65, f"Risk category: {_risk_category(score)}")
    c.drawString(60, summary_y - 80, f"Generated on: {generated_at}")

    # Embed X-ray thumbnail
    try:
        img = ImageReader(image_path)
        c.drawImage(img, width - 260, height - 250, width=200, height=200, preserveAspectRatio=True, anchor="c")
    except Exception:
        pass

    # Recommendations
    rec_y = summary_y - 120
    c.setFont("Helvetica-Bold", 12)
    c.drawString(50, rec_y, "Recommendations")
    c.setFont("Helvetica", 10)
    if recommendations:
        line_y = rec_y - 20
        for rec in recommendations[:6]:
            c.drawString(60, line_y, f"• {rec}")
            line_y -= 14
            if line_y < 80:
                _draw_footer(c, 1, width)
                c.showPage()
                c.setFont("Helvetica", 10)
                line_y = height - 80
        summary_y = line_y - 10
    else:
        c.drawString(60, rec_y - 20, "No clinical recommendations available for this scan.")
        summary_y = rec_y - 40

    _draw_footer(c, 1, width)
    c.showPage()

    # Detailed feature review page
    c.setFont("Helvetica-Bold", 18)
    c.drawString(50, height - 60, "Detailed feature review")
    c.setFont("Helvetica", 10)
    c.drawString(50, height - 80, "Top feature weights are shown below to support clinical review and follow-up.")

    # Normalize features to a list to avoid numpy array truth-value issues
    features_list = list(features) if features is not None else []
    if len(features_list) > 0:
        table_x = 50
        table_y = height - 110
        c.setFont("Helvetica-Bold", 10)
        c.drawString(table_x, table_y, "Feature")
        c.drawString(table_x + 140, table_y, "Value")
        c.setFont("Helvetica", 10)
        table_y -= 18
        for idx, feature_value in enumerate(features_list[:18]):
            try:
                val = float(feature_value)
            except Exception:
                val = 0.0
            c.drawString(table_x, table_y, f"Feature {idx + 1}")
            c.drawString(table_x + 140, table_y, f"{val:.5f}")
            table_y -= 16
            if table_y < 80:
                _draw_footer(c, 2, width)
                c.showPage()
                c.setFont("Helvetica", 10)
                table_y = height - 80
    else:
        c.drawString(50, height - 110, "Feature details were not available for this report.")

    _draw_footer(c, 2, width)
    c.save()

    return report_name